name: 'RAVN Fastlane Action for iOS'
branding:
  icon: check-circle
  # noinspection YAMLSchemaValidation
  color: black
description: 'Execute fastlane pipeline for iOS'
inputs:
  build-lane:
    description: 'The build lane that should be executed (values: beta, release)'
    required: true
  enforced-branch:
    description: 'Branch to enforce, recommended (supports regex)'
    required: false
  build-number:
    description: |
      Which build number strategy to use: `store` to increment previous published build, `github` to use run number
      as build number (default), or empty to use local auto-increment.
    required: false
    default: 'github'
  commit-increment:
    description: 'Whether or not to commit and push version increment'
    required: false
    default: 'false'
  publish-build:
    description: 'Whether or not to publish build artifacts to the Play Store'
    required: false
    default: 'true'
  upload-artifacts:
    description: 'Whether or not to upload output artifacts to GitHub Actions'
    required: false
    default: 'false'
  app-identifier:
    description: 'App Store application bundle identifier'
    required: true
  team-id:
    description: 'App Store Connect Team ID (if any)'
    required: false
  itc-team-id:
    description: 'iTunes Connect Team ID (if any)'
    required: false
  scheme:
    description: 'iOS project scheme to build'
    required: true
  configuration:
    description: 'iOS project configuration to use'
    required: false
    default: 'Release'
  xcodeproj:
    description: 'Path to main XCode project'
    required: true
  xcworkspace:
    description: 'Path to main XCode workspace'
    required: false
  podfile:
    description: 'Path to the Podfile (if any) or parent dir, if not defined will try to look for one based on the path of the Xcode project'
    required: false
  apple-key-id:
    description: 'Apple App Store Connect Key ID'
    required: true
  apple-issuer-id:
    description: 'Apple App Store Connect Issuer ID'
    required: true
  apple-key-base64:
    description: 'Apple App Store Connect Key contents (.p8) in base64'
    required: true
  enterprise:
    description: 'Whether or not it is Apple Enterprise'
    required: false
    default: 'false'
  match-password:
    description: 'Password to encrypt/decrypt certificates using match'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2'
        bundler-cache: true
    - id: create-apple-key-file
      if: ${{ inputs.apple-key-base64 != '' }}
      shell: bash
      run: |
        echo "${{ inputs.apple-key-base64 }}" | base64 -d > __apple_key.p8
        echo "apple-key-file=$(pwd)/__apple_key.p8" >> $GITHUB_OUTPUT
    - id: run-fastlane
      shell: bash
      run: ${{ github.action_path }}/fastlane.sh
      env:
        BUILD_LANE: ${{ inputs.build-lane }}
        MATCH_PASSWORD: ${{ inputs.match-password }}
        RUN_NUMBER: ${{ github.run_number }}
        BUILD_NUMBER_STRATEGY: ${{ inputs.build-number }}
        FL_ENFORCED_BRANCH: ${{ inputs.enforced-branch }}
        FL_COMMIT_INCREMENT: ${{ inputs.commit-increment }}
        FL_PUBLISH_BUILD: ${{ inputs.publish-build }}
        FL_PACKAGE_NAME: ${{ inputs.package-name }}
        FL_APP_IDENTIFIER: ${{ inputs.app-identifier }}
        FL_TEAM_ID: ${{ inputs.team-id }}
        FL_ITC_TEAM_ID: ${{ inputs.itc-team-id }}
        FL_IOS_SCHEME: ${{ inputs.scheme }}
        FL_IOS_CONFIGURATION: ${{ inputs.configuration }}
        FL_XCODE_PROJ: ${{ inputs.xcodeproj }}
        FL_XCODE_WORKSPACE: ${{ inputs.xcworkspace }}
        FL_IOS_PODFILE: ${{ inputs.podfile }}
        FL_APPLE_KEY_ID: ${{ inputs.apple-key-id }}
        FL_APPLE_ISSUER_ID: ${{ inputs.apple-issuer-id }}
        FL_APPLE_KEY_FILE: ${{ steps.create-apple-key-file.outputs.apple-key-file }}
        FL_APPLE_ENTERPRISE: ${{ inputs.enterprise }}
    - id: upload-artifacts
      if: ${{ inputs.upload-artifacts == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: artifacts/
